name: Sync changes

on:
  push:
    branches:
      - master

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build & deploy to github
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin gh-pages
          make deploy
